### DISCUSSION TITLE
Jitsi on Kubernetes - The given hostname does not exist in the config ....?

### DISCUSSION THREAD

**Discussion by rsoika** [jitsi-contrib/jitsi-kubernetes-operator#15] [Q&A]
I am running jitsi on kubernetes with the jitsi-kubernetes-operator since more than a year. 
Now I run into a strange problem. When I try to register a user with 

    prosodyctl --config /config/prosody.cfg.lua register admin my-host.foo.com

I get the message: 

    The given hostname does not exist in the config

I didn't find out how or where to set this hostname. 
My deployment setting looks like this:

```
apiVersion: apps.jit.si/v1alpha1
kind: Jitsi
metadata:
  name: my-jitsi
  namespace: jitsi  
spec:
  domain: my-host.foo.com
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/ingress.class: "nginx"   
    enabled: true
    tls: true
  jibri:
    enabled: true
    replicas: 1
  jvb:
    gracefulShutdown: true
    strategy:
      replicas: 1
      type: static
  region: europe
  timezone: Europe/Berlin
  variables:
    ENABLE_BREAKOUT_ROOMS: "1"
    ENABLE_AUTH: "1"
    ENABLE_GUESTS: "1"
```
    

Can someone give me a hint what I am missing?
I never have had this message in the past .
