### DISCUSSION TITLE
How to enable Auth?

### DISCUSSION THREAD

**Discussion by rsoika** [jitsi-contrib/jitsi-kubernetes-operator#16] [Q&A] [answered]
Can someone give a short example how to enable authentication for meeting rooms?

**Comment by rsoika** [comment, marked as answer]
Ok - short answer:

After you installed jitsi using the operator project create an additional `deployment.yaml` file to overwrite settings. 

Example:

```yaml
apiVersion: apps.jit.si/v1alpha1
kind: Jitsi
metadata:
  name: foo-jitsi
  namespace: jitsi  
spec:
  domain: meeting.foo.com
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/ingress.class: "nginx"
    enabled: true
    tls: true
  jibri:
    enabled: true
    replicas: 1
  jvb:
    gracefulShutdown: true
    strategy:
      replicas: 1
      type: static
  region: europe
  timezone: Europe/Berlin
  variables:
    ENABLE_BREAKOUT_ROOMS: "1"
    ENABLE_AUTH: "1"
    ENABLE_GUESTS: "1"
```

This example sets a public internet name `https://meeting.foo.com` via a nginx reverse-proxy and letsencrypt and secures the meeting rooms by enabling authentication. This means you need to open a meeting by a login with user name/password

Next you can open a shell on the `prosody` container and use the following command to create a new user 'sepp' with the password 123


    prosodyctl --config /config/prosody.cfg.lua register sepp meet.jitsi 123
