### DISCUSSION TITLE
How to intall in a custom Kubernetes Cluster?

### DISCUSSION THREAD

**Discussion by rsoika** [jitsi-contrib/jitsi-kubernetes-operator#9] [Q&A] [answered]
Hi,
I did not understand the instructions in the README.md file. what does the following command do?? 

    kubectl apply -f https://raw.githubusercontent.com/jitsi-contrib/jitsi-kubernetes-operator/master/deploy/jitsi-operator.yaml

How can I configure my own Web Address for the Jitsi server? I guess I need somehow a Ingres configuration? Also the files in the /config/samples folder are not clear to me? How should I customize these files an how are these files applied during the deployment?

Can someone give me a hint how to setup my own jitsi server using this kubernetes-obperator?

**Comment by hrenard** [comment, marked as answer]
Hey !
Sorry the documentation is still missing...
The above command will install the Custom Resource Definition and the operator in your k8s cluster.
Then you can deploy a jitsi cluster simply with a `kubectl apply` of :
```yaml
apiVersion: apps.jit.si/v1alpha1
kind: Jitsi
metadata:
  name: my-jitsi
spec:
  domain: meet.my-domain.com
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    enabled: true
    tls: true
  jibri:
    enabled: true
    replicas: 1
  jvb:
    gracefulShutdown: true
    strategy:
      replicas: 1
      type: static
  region: europe
  timezone: Europe/Paris
  variables:
    ENABLE_BREAKOUT_ROOMS: "1" 
  ```
  For now, we rely on the nginx-ingresss controller's annotations.
  Every environment variables of the docker jitsi can be used in the variables field (except the ones managed by the operator).

**Comment by rsoika** [comment]
Thanks, yes we are also running nginx-ingress. So I will try this out and give you feedback...

**Comment by rsoika** [comment]
ok, everything seems to work fine.
The installation of the operator was no problem.

Installing my custom deployment also worked well. I just needed to rename the `cert-manager.io/cluster-issuer` from `letsencrypt` to `letsencrypt-prod` because of my cluster setup.

In addition I added a namespace to my deployment config which was at the end no problem.

Great Work!!
I think I will update the https://github.com/jitsi-contrib/jitsi-kubernetes page to use this operator as the installation seems to be more easy. Or maybe I describe this as an alternative way to run Jitsi on Kubernetes

**Comment by hrenard** [comment]
Wonderful, thank you !

We, [IndieHosters](https://indiehosters.net/) use it in production to host multiple Jitsi instances. You can chat with us on [Matrix](https://matrix.to/#/#libresh:liiib.re), if you want.
Unfortunately we haven't had the time to advocate the operator to the community. But we believe, although building an operator is more work, that it's the way to go for managing things at scale.

I'll try to clean up the readme to list features like autoscaling, graceful upgrade (upgrading when there are no conferences)... And add a roadmap, we want to support shared JVB & Jibri pools, add Jigasi... And some documentation.

**Comment by rsoika** [comment]
Another point you probably already know:

I protected my installation with a password for meetings by adding the following two environment variables:

```yaml
  variables:
    ENABLE_BREAKOUT_ROOMS: "1"
    # Close Rooms with password
    ENABLE_AUTH: "1"
    ENABLE_GUESTS: "1"
    # Set admin password in the prosody server with:
    #  prosodyctl --config /config/prosody.cfg.lua register admin [YOUR-JITSI-DOMAIN]
```

This also worked great out of the box.
