### ISSUE TITLE
Make maxUnavailable more reliable to all use cases.

### ISSUE THREAD

**Issue by pierreozoux** [jitsi-contrib/jitsi-kubernetes-operator#3]
Currently, if you have 2 nodes with 2 jvbs on each node, it is impossible for the operator to update jvbs.

It is due to the strategy:

```
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
```

In this case, it has to be changed to 50% so that kubernetes will be able to kill one pod after another.
