### ISSUE TITLE
How to intall in a custom Kubernetes Cluster?

### ISSUE THREAD

**Issue by rsoika** [jitsi-contrib/jitsi-kubernetes-operator#8]
Hi,
I did not understand the instructions in the README.md file. what does the following command do?? 

    kubectl apply -f https://raw.githubusercontent.com/jitsi-contrib/jitsi-kubernetes-operator/master/deploy/jitsi-operator.yaml

How can I configure my own Web Address for the Jitsi server? I guess I need somehow a Ingres configuration? Also the files in the /config/samples folder are not clear to me? How should I customize these files an how are these files applied during the deployment?

Can someone give me a hint how to setup my own jitsi server using this kubernetes-obperator?

**Comment by hrenard** [comment]
Hey !
Sorry the documentation is still missing...
The above command will install the Custom Resource Definition and the operator in your k8s cluster.
Then you can deploy a jitsi cluster simply with a `kubectl apply` of :
```yaml
apiVersion: apps.jit.si/v1alpha1
kind: Jitsi
metadata:
  name: my-jitsi
spec:
  domain: meet.my-domain.com
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    enabled: true
    tls: true
  jibri:
    enabled: true
    replicas: 1
  jvb:
    gracefulShutdown: true
    strategy:
      replicas: 1
      type: static
  region: europe
  timezone: Europe/Paris
  variables:
    ENABLE_BREAKOUT_ROOMS: "1" 
  ```
  For now, we rely on the nginx-ingresss controller's annotations.
  Every environment variables of the docker jitsi can be used in the variables field (except the ones managed by the operator).
